//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.26 at 04:43:09 PM CET 
//


package com.computationalcluster.common.messages;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComponentType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ComponentType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="TaskManager"/>
 *     &lt;enumeration value="ComputationalNode"/>
 *     &lt;enumeration value="CommunicationServer"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ComponentType")
@XmlEnum
public enum ComponentType {

    @XmlEnumValue("TaskManager")
    TASK_MANAGER("TaskManager"),
    @XmlEnumValue("ComputationalNode")
    COMPUTATIONAL_NODE("ComputationalNode"),
    @XmlEnumValue("CommunicationServer")
    COMMUNICATION_SERVER("CommunicationServer");
    private final String value;

    ComponentType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ComponentType fromValue(String v) {
        for (ComponentType c: ComponentType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
