//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.26 at 04:43:09 PM CET 
//


package com.computationalcluster.common.messages;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.computationalcluster.common.messages package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.computationalcluster.common.messages
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Status }
     * 
     */
    public Status createStatus() {
        return new Status();
    }

    /**
     * Create an instance of {@link SolvePartialProblems }
     * 
     */
    public SolvePartialProblems createSolvePartialProblems() {
        return new SolvePartialProblems();
    }

    /**
     * Create an instance of {@link Solutions }
     * 
     */
    public Solutions createSolutions() {
        return new Solutions();
    }

    /**
     * Create an instance of {@link NoOperation }
     * 
     */
    public NoOperation createNoOperation() {
        return new NoOperation();
    }

    /**
     * Create an instance of {@link Register }
     * 
     */
    public Register createRegister() {
        return new Register();
    }

    /**
     * Create an instance of {@link NoOperation.BackupCommunicationServers }
     * 
     */
    public NoOperation.BackupCommunicationServers createNoOperationBackupCommunicationServers() {
        return new NoOperation.BackupCommunicationServers();
    }

    /**
     * Create an instance of {@link Solutions.SolutionsList }
     * 
     */
    public Solutions.SolutionsList createSolutionsSolutionsList() {
        return new Solutions.SolutionsList();
    }

    /**
     * Create an instance of {@link SolvePartialProblems.PartialProblems }
     * 
     */
    public SolvePartialProblems.PartialProblems createSolvePartialProblemsPartialProblems() {
        return new SolvePartialProblems.PartialProblems();
    }

    /**
     * Create an instance of {@link Status.Threads }
     * 
     */
    public Status.Threads createStatusThreads() {
        return new Status.Threads();
    }

    /**
     * Create an instance of {@link RegisterResponse }
     * 
     */
    public RegisterResponse createRegisterResponse() {
        return new RegisterResponse();
    }

    /**
     * Create an instance of {@link Register.Type }
     * 
     */
    public Register.Type createRegisterType() {
        return new Register.Type();
    }

    /**
     * Create an instance of {@link Register.SolvableProblems }
     * 
     */
    public Register.SolvableProblems createRegisterSolvableProblems() {
        return new Register.SolvableProblems();
    }

    /**
     * Create an instance of {@link SolveRequest }
     * 
     */
    public SolveRequest createSolveRequest() {
        return new SolveRequest();
    }

    /**
     * Create an instance of {@link Error }
     * 
     */
    public Error createError() {
        return new Error();
    }

    /**
     * Create an instance of {@link SolveRequestResponse }
     * 
     */
    public SolveRequestResponse createSolveRequestResponse() {
        return new SolveRequestResponse();
    }

    /**
     * Create an instance of {@link SolutionRequest }
     * 
     */
    public SolutionRequest createSolutionRequest() {
        return new SolutionRequest();
    }

    /**
     * Create an instance of {@link DivideProblem }
     * 
     */
    public DivideProblem createDivideProblem() {
        return new DivideProblem();
    }

    /**
     * Create an instance of {@link NoOperation.BackupCommunicationServers.BackupCommunicationServer }
     * 
     */
    public NoOperation.BackupCommunicationServers.BackupCommunicationServer createNoOperationBackupCommunicationServersBackupCommunicationServer() {
        return new NoOperation.BackupCommunicationServers.BackupCommunicationServer();
    }

    /**
     * Create an instance of {@link Solutions.SolutionsList.Solution }
     * 
     */
    public Solutions.SolutionsList.Solution createSolutionsSolutionsListSolution() {
        return new Solutions.SolutionsList.Solution();
    }

    /**
     * Create an instance of {@link SolvePartialProblems.PartialProblems.PartialProblem }
     * 
     */
    public SolvePartialProblems.PartialProblems.PartialProblem createSolvePartialProblemsPartialProblemsPartialProblem() {
        return new SolvePartialProblems.PartialProblems.PartialProblem();
    }

    /**
     * Create an instance of {@link Status.Threads.Thread }
     * 
     */
    public Status.Threads.Thread createStatusThreadsThread() {
        return new Status.Threads.Thread();
    }

}
