//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.26 at 04:43:09 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.mini.pw.edu.pl/ucc/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.computationalcluster.common.messages;
