//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.26 at 04:43:09 PM CET 
//


package com.computationalcluster.common.messages;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Type">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.mini.pw.edu.pl/ucc/>ComponentType">
 *                 &lt;attribute name="port" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SolvableProblems">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ProblemName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ParallelThreads" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *         &lt;element name="Deregister" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "type",
    "solvableProblems",
    "parallelThreads",
    "deregister",
    "id"
})
@XmlRootElement(name = "Register")
public class Register {

    @XmlElement(name = "Type", required = true)
    protected Register.Type type;
    @XmlElement(name = "SolvableProblems", required = true)
    protected Register.SolvableProblems solvableProblems;
    @XmlElement(name = "ParallelThreads")
    @XmlSchemaType(name = "unsignedByte")
    protected short parallelThreads;
    @XmlElement(name = "Deregister")
    protected Boolean deregister;
    @XmlElement(name = "Id")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger id;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link Register.Type }
     *     
     */
    public Register.Type getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link Register.Type }
     *     
     */
    public void setType(Register.Type value) {
        this.type = value;
    }

    /**
     * Gets the value of the solvableProblems property.
     * 
     * @return
     *     possible object is
     *     {@link Register.SolvableProblems }
     *     
     */
    public Register.SolvableProblems getSolvableProblems() {
        return solvableProblems;
    }

    /**
     * Sets the value of the solvableProblems property.
     * 
     * @param value
     *     allowed object is
     *     {@link Register.SolvableProblems }
     *     
     */
    public void setSolvableProblems(Register.SolvableProblems value) {
        this.solvableProblems = value;
    }

    /**
     * Gets the value of the parallelThreads property.
     * 
     */
    public short getParallelThreads() {
        return parallelThreads;
    }

    /**
     * Sets the value of the parallelThreads property.
     * 
     */
    public void setParallelThreads(short value) {
        this.parallelThreads = value;
    }

    /**
     * Gets the value of the deregister property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDeregister() {
        return deregister;
    }

    /**
     * Sets the value of the deregister property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDeregister(Boolean value) {
        this.deregister = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ProblemName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "problemName"
    })
    public static class SolvableProblems {

        @XmlElement(name = "ProblemName")
        protected List<String> problemName;

        /**
         * Gets the value of the problemName property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the problemName property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProblemName().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getProblemName() {
            if (problemName == null) {
                problemName = new ArrayList<String>();
            }
            return this.problemName;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.mini.pw.edu.pl/ucc/>ComponentType">
     *       &lt;attribute name="port" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Type {

        @XmlValue
        protected ComponentType value;
        @XmlAttribute(name = "port")
        @XmlSchemaType(name = "unsignedShort")
        protected Integer port;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link ComponentType }
         *     
         */
        public ComponentType getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link ComponentType }
         *     
         */
        public void setValue(ComponentType value) {
            this.value = value;
        }

        /**
         * Gets the value of the port property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getPort() {
            return port;
        }

        /**
         * Sets the value of the port property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setPort(Integer value) {
            this.port = value;
        }

    }

}
